# Configuração básica do site
baseURL = "https://nildo.blog.br/"
languageCode = "pt-br"
title = "Blog do Nildo"
theme = "not-much"
contentDir = "content"
dataDir = "data"
assetDir = "static"
publishDir = "public"
description = "Desabafando como se ainda fosse 1999"
author = "Nildo Amorim"
copyright = "Todos os direitos reservados © {year}"

[markup]
  [markup.highlight]
    style = 'catpuccin'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
palette = "catpuccin"
showThemeNotice = false
showPostsSummary = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

# Navigation
[menu]
  [[menu.main]]
    identifier = "inicio"
    name = "inicio"
    title = "inicio"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts"
    weight = 3
  
  [[menu.main]]
    identifier = "sobre"
    name = "sobre"
    title = "sobre"
    url = "/sobre"
    weight = 2

  [[menu.main]]
    identifier = "recomendações"
    name = "recomendações"
    title = "recomendações"
    url = "/recomendacoes"
    weight = 4

  [[menu.main]]
    identifier = "newsletter"
    name = "newsletter"
    title = "newsletter"
    url = "/newsletter"
    weight = 5

