# Configuração básica do site
baseURL = "https://nildo.blog.br/"
languageCode = "pt-br"
title = "Blog do Nildo"
theme = "not-much"
contentDir = "content"
dataDir = "data"
assetDir = "static"
publishDir = "public"
description = "Desabafando como se ainda fosse 1999"
author = "Nildo Amorim"
copyright = "Todos os direitos reservados © {year}"

[markup]
  [markup.highlight]
    style = 'dracula'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
theme = "dark"
palette = "catpuccin"
showThemeNotice = true
showPostsSummary = true
numberOfPosts = 5

# Navigation
[menu]
  [[menu.main]]
    identifier = "inicio"
    name = "inicio"
    title = "inicio"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts"
    weight = 3
  
  [[menu.main]]
    identifier = "sobre"
    name = "sobre"
    title = "sobre"
    url = "/sobre"
    weight = 2

