# Configuração básica do site
baseURL = "https://nildo.blog.br/"
languageCode = "pt-br"
title = "Blog do Nildo"
theme = "not-much"
description = "Desabafando como se ainda fosse 1999"
copyright = "Todos os direitos reservados © {year}"

[markup]
  [markup.highlight]
    style = 'catpuccin'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
theme = "dark"
palette = "dracula"
showThemeNotice = true
showPostsSummary = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

# Navigation
[menu]
  [[menu.main]]
    identifier = "inicio"
    name = "inicio"
    title = "inicio"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "blog"
    name = "blog"
    title = "blog"
    url = "/blog"
    weight = 2
  
  [[menu.main]]
    identifier = "sobre"
    name = "sobre"
    title = "sobre"
    url = "/sobre"
    weight = 4

  [[menu.main]]
    identifier = "recomendações"
    name = "recomendações"
    title = "recomendações"
    url = "/recomendacoes"
    weight = 3



